### ISSUE TITLE
Not work on hassio 2021.7.0

### ISSUE THREAD

**Issue by davidbenucci** [ykmn/hacs-yeelight_v2#1]
I've just installed it via hacs but if i add an integration Yeelight v2 is not found Why? Thanks

**Comment by Psychoses** [comment]
i'm on : core-2021.7.2
if you install via hacs, u will get on log

```
ERROR
The custom integration 'yeelight_v2' does not have a valid version key (None) in the manifest file and was blocked from loading. 
See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details
```

Replace the `manifest.json` with this one : https://raw.githubusercontent.com/Silvest89/yeelight_v2/main/manifest.json do the trick.

**Comment by ykmn** [comment]
Updated.
